spring:
  application:
    name: laocai
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    web-application-type: none
    keep-alive: true
  profiles:
    active: local
  ai:
    chat:
      observations:
        log-prompt: true

logging:
  level:
    root: info
    indi.dkx.laocai: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %highlight(%5p) %clr([%t]){magenta} %clr(%-40.40logger{39}){cyan} %clr(>){faint} %m%n"